services:
  postgres:
    image: postgres:13
    container_name: taskquest-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER_PROD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PROD}
      POSTGRES_DB: ${POSTGRES_DB_PROD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskquest-backend
    restart: always
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER_PROD}
      DB_PASSWORD: ${POSTGRES_PASSWORD_PROD}
      DB_NAME: ${POSTGRES_DB_PROD}
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.taskquest_api.rule=Host(`taskquest-api.yourdomain.com`)"
      - "traefik.http.routers.taskquest_api.entrypoints=websecure"
      - "traefik.http.routers.taskquest_api.tls.certresolver=myresolver"
      - "traefik.http.routers.taskquest_api.service=svc_taskquest_api"
      - "traefik.http.services.svc_taskquest_api.loadbalancer.server.port=3000"

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: taskquest-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.taskquest.rule=Host(`taskquest.yourdomain.com`)"
      - "traefik.http.routers.taskquest.entrypoints=websecure"
      - "traefik.http.routers.taskquest.tls.certresolver=myresolver"
      - "traefik.http.routers.taskquest.service=svc_taskquest"
      - "traefik.http.services.svc_taskquest.loadbalancer.server.port=80"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: